# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  config.vm.define "generic-ops" do |d|
    d.vm.box = "generic-ops-ol73"
    d.vm.hostname = "generic-ops"
    d.vm.network "private_network", ip: "10.100.198.225"
    #d.vm.provision :shell, path: "scripts/bootstrap_ol7_headless_users_env.sh", env: {"http_proxy" => "#{ENV['http_proxy']}", "https_proxy" => "#{ENV['https_proxy']}"}
    #d.vm.provision :shell, path: "scripts/bootstrap_ol7_oracle_opc_cli.sh", env: {"http_proxy" => "#{ENV['http_proxy']}", "https_proxy" => "#{ENV['https_proxy']}"}
    #d.vm.provision :shell, path: "scripts/bootstrap_ol7_oracle_psm_cli.sh", env: {"http_proxy" => "#{ENV['http_proxy']}", "https_proxy" => "#{ENV['https_proxy']}"}
    d.vm.provider "virtualbox" do |v|
      v.name = "generic-ops-ol73"
      v.gui = true
      v.memory = 4096
      v.cpus = 1
      v.customize ["modifyvm", :id, "--vram", "12"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
      v.customize ["modifyvm", :id, "--description", "Oracle Linux 7.3 (UEKR4) VM image for DevOps 2.0 'generic-ops-ol73' headless box."]
      v.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "1", "--device", "0", "--type", "dvddrive", "--medium", "emptydrive"]
      # mount windows shared folder.
      #v.customize ["sharedfolder", "add", :id, "--name", "shared", "--hostpath", "I:/shared", "--automount"]
      # mount macosx shared folder.
      #v.customize ["sharedfolder", "add", :id, "--name", "shared", "--hostpath", "/Volumes/g-drive/shared", "--automount"]
    end
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.iso_path = "http://download.virtualbox.org/virtualbox/$VBOX_VERSION/VBoxGuestAdditions_$VBOX_VERSION.iso"
    config.vbguest.auto_update = true
    config.vbguest.no_install = false
    config.vbguest.no_remote = false
    config.vbguest.auto_reboot = true
  end
end
