os_name                 = "rockylinux"
os_version              = "10.2"
os_arch                 = "x86_64"
iso_url                 = "https://download.rockylinux.org/pub/rocky/10.2/isos/x86_64/Rocky-10.2-x86_64-dvd1.iso"
iso_checksum            = "file:https://download.rockylinux.org/pub/rocky/10.2/isos/x86_64/CHECKSUM"
parallels_guest_os_type = "rhel"
vbox_guest_os_type      = "Oracle_64"
vmware_guest_os_type    = "centos-64"
utm_vm_icon             = "linux"
boot_command            = ["<wait><up><wait>e<wait><down><down><end><wait> inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/rhel/ks.cfg inst.repo=https://download.rockylinux.org/pub/rocky/10/BaseOS/x86_64/os/ <leftCtrlOn>x<leftCtrlOff>"]
user_docker_profile     = "false"
vm_hostname             = "lpad-rockylinux102"
